### ISSUE TITLE
Improve filters section: Third Party and Differences between jinja

### ISSUE THREAD

**Issue by Mparaiso** [mozilla/nunjucks-docs#23]
We all know what place is npmjs.org, a place where it's just too difficult to find relevant,good quality packages among 90% of unuseful ones .If it hadnt been for HackerNews,i would never have heard of nunjucks.

What would be cool is to maintain a list of thirdparty filters directly in the docs,after the builtins ,for instance,a date filter is the first thing I was looking for when trying nunjucks.

It will encourage people creating new filters to participate directly to the docs too.

-- 

Another example by yoshokatana:

I was looking through the docs for the replace filter, since it now supports regex, but couldn't find anything in Jinja about it. After diving into the github issues I finally figured out the syntax (r/body/flags rather than javascript's /body/flags), and I wanted to add that to the documentation, but it looks like nunjucks just links to Jinja's docs.

It seems like, at least for the filters, Nunjucks is diverting from Jinja. Probably more than just the little issue I saw. Should separate api docs be maintained, or should there be a push to update Jinja to conform to Nunjucks' spec?

**Comment by jlongster** [comment]
Sorry I'm just now finally fixing up the docs. We should definitely begin our own filter docs. I'm in the process of moving the docs over to https://github.com/mozilla/nunjucks/tree/master/docs, and I'd love help with that!

**Comment by jlongster** [comment]
Closing this issue because we're moving everything over there
