### ISSUE TITLE
Fix navigation items and make it more consistent

### ISSUE THREAD

**Issue by fvsch** [mozilla/nunjucks-docs#6]
There are two main navigation bars for the Nunjucks documentation site, defined in the `page.html` and `subpage.html` layouts. They don’t really match.

On the home page we have:

- Download [broken!]
- Github
- Templating Docs
- API Docs
- FAQ

On the other pages:

- Download [broken!]
- Github
- Docs [with dropdown]

If the documentation structure with 4 pages is final, I suggest using the name navigation for both layouts:

- Getting Started
- Templating Docs
- API Docs
- FAQ
- Github

The `subpage.html` layout could be simplified and look like this:

![nunjucks-docs-nav](https://f.cloud.github.com/assets/243601/1459966/852b17e2-4404-11e3-843e-ac1f48ca5401.png)

**Comment by jlongster** [comment]
I haven't had time to work on this and probably won't. Moving the docs over to https://github.com/mozilla/nunjucks/tree/master/docs if someone wants to pick this up
